version: 0.1

phases:
    install:
        commands:
            - apt-get update -y
            - apt-get install -y npm
            - nodejs --version
    build:
        commands:
            - npm install
            - npm run build

    post_build:
        commands:
            - echo "Upload to Lambda"
            - echo "Upload to S3"
