version: 0.1

phases:
    install:
        commands:
            - apt-get update -y
            - wget -qO- https://deb.nodesource.com/setup_6.x | sudo bash -
            - apt-get install -y nodejs npm
            - which nodejs
            - which node

    build:
        commands:
            - npm install
            - npm run build

    post_build:
        commands:
            - echo "Upload to Lambda"
            - echo "Upload to S3"
