version: 0.1

phases:
    install:
        commands:
            - apt-get update -y
            - wget -qO- https://deb.nodesource.com/setup_6.x | sudo bash -
            - apt-get install -y nodejs

    build:
        commands:
            - npm install
            - npm run build

    post_build:
        commands:
            - aws s3 cp --acl public-read --recursive web/ s3://$WEBSITE_UPLOAD_BUCKET/
            - echo "https://s3.amazonaws.com/$WEBSITE_UPLOAD_BUCKET/index.html"
